packages:
  - packages/*
  - examples/*
  - apps/*

onlyBuiltDependencies:
  - '@tailwindcss/oxide@4.1.17'
  - esbuild@0.25.12
  - esbuild@0.27.1
  - sharp@0.34.5
  - unrs-resolver@1.11.1

strictDepBuilds: true

verifyDepsBeforeRun: true
